### ISSUE TITLE
場所を決める

### ISSUE THREAD

**Issue by pndcat** [kosenconf-2015-tokyo/kosenconf#1]
現在の候補：電通大 B棟 
収容人数400人 
#### 新春カンファで使用した都立荒川は？
- 新春カンファ(2012年)では「高専カンファレンス 2010秋 in 東京」のときに借りたツテ（鈴木先生）から借りることができた  
- ここすごく広くてよかったが，今も借りれるかわからない  
- とりあえず電通大無理だったら，お問い合わせする
#### できれば企業のスペースは借りたくないです（なっちゃんの意見）
- 企業の色が出るような高専カンファじゃなくて，高専カンファらしい高専カンファがしたい  
- 場所がなければ企業様にお願いすることもありえる

**Comment by pndcat** [comment]
電通大の事務に聞いた

#### 2016/1/16 - 1/17 だったら
- センター試験とかぶってるから無理

#### そのたの日程の場合
- **基本的にサークルか、先生だけ施設を借りられる**
- サークルの場合:大学公認
- 先生:先生の責任の元、借りられる
- 個人は無理

#### 問題点
- 少なくとも2016/1/16 - 1/17の場合、電通大で不可能
- なっちゃん:サークルは書道部(だけどそんなに行ってないし、明らかに書道部の人関係ないのに、書道部の名前で借りられるのかわからない)
- とちくじ:サークル未所属

#### 可能性
- 2016/1/16 - 1/17 にやるのならば、大学以外の場所でやらないといけない(高専?企業?市の施設など?)
- 一週間ずらし、どこかのサークルの名前で電通大を借りる
- 一週間ずらし、先生に協力を求め電通大を借りる

**Comment by pndcat** [comment]
とちくじくんが目をつけていた先生にメールを投げたところ，前向きな返事が頂けました．
明後日（7/9 木）実際に先生とお話をしてきます（with とちくじ）

とりあえず，先生には2016年1月23日 - 2016年1月24日 （土日両日）ということで話しています．
もし，これで決まるんだったら日程はセンター試験 1週間後の上記になってしまうけど大丈夫ですかね？

**Comment by pndcat** [comment]
#### 報告

**電通大の先生が，高専カンファレンスに協力をしてくれ，B棟を借りることができます**

#### 全員に確認
- 2016年1月23日 - 2016年1月24日の週で良いか？（新春より1週間後の週）
- 2日開催で良いか？
- 借用時間（例：8:00〜20:00とか）はどうする？

#### 上記内容の確認の期限
- 明日（7/9 金）先生に上記の内容をメールで出したいので，本日（7/8 木）までに答えて下さい（遅くても7/9 12:00まで）
- このissueにコメントか，slackに投げて下さいー

**Comment by mactkg** [comment]
[![LGTM](http://lgtm.in/p/6pbrqJoFn)](http://lgtm.in/i/6pbrqJoFn)

ありがたいですね、、、!! 二日開催は賛成です。日程も良いと思います。8:00-20:00でお借りできれば十分ではと思いました。

**Comment by pndcat** [comment]
途中報告．

先生は海外出張中です．
本日，「帰国次第、予約の手続きを取ります」とメール来ました．
帰国次第がいつなのかわからないのですが，また連絡来たら報告しますー．

**Comment by pndcat** [comment]
先生から教務課に確認取り，連絡が来ました．
1/23-1/24は不可でした(゜゜) 

# 以下引用

2016/1/23(土) - 2016/1/24(日)は大学入試センター試験の追・再試験日となっており、
大変申し訳ございませんが、教室予約をお取りすることができません。

**Comment by pndcat** [comment]
## B棟使用不可の日程について

先生から1・2月のB棟の使用不可の日程について，メールが来ました．
今は12月案が出ているので，あまり関係ないかもしれませんが，とりあえず報告します．

以下引用

1/11（月・祝）　　  TOEIC－IPテスト　A棟・B棟・C棟 
1/16（土）・17（日）センター試験 
1/23（土）・24（日) センター試験追・再試験日 
1/31（日）　　　　　TOEIC公開テスト　　 A棟・B棟・C棟・旧C棟 
2/19（金）～3/31（木）B201・B202照明改修工事予定

**Comment by pndcat** [comment]
会場、仮押さえできました

日程 12/19,12/20
場所 電通大B棟

以下引用

Ｂ棟の予約ですが下記で仮予約しました。
”仮”となっている理由ですが、`Ｋ課程の後期授業の教室割振が10月上旬になら
ないと正式決定しないからです。
例年の状況からすると土曜日にＢ棟１階の教室を使うことはあっても、２階は使
わないようなので、大丈夫だと思います。

## B棟教室仮予約

日程：12/19（土）、20（日）
時間：8:00 - 20:00
場所：電通大 B棟（B101, B102, B201, B202）
