### ISSUE TITLE
時間を決める

### ISSUE THREAD

**Issue by pndcat** [kosenconf-2015-tokyo/kosenconf#10]
本会
土曜日：？？-？？
日曜日：？？-？？

懇親会
おそらく土曜日だよね

ちなみに，B棟の申請は
土日両日：8:00 - 20:00

**Comment by mactkg** [comment]
第二回MTGでタイムテーブル決定した
https://github.com/kosenconf-2015-tokyo/kosenconf/wiki/meeting002_20150906
