### ISSUE TITLE
ポスターに書く内容決める

### ISSUE THREAD

**Issue by pndcat** [kosenconf-2015-tokyo/kosenconf#13]
参考一覧

[新春・高専カンファレンス2012 in 東京](http://kosenconf.jp/?plugin=attach&refer=038tokyo&openfile=poster_kc038.jpg)
[高専カンファin奈良2](http://kosenconf.jp/?plugin=attach&refer=054nara&openfile=%E9%AB%98%E5%B0%82%E3%82%AB%E3%83%B3%E3%83%95%E3%82%A1%E3%83%AC%E3%83%B3%E3%82%B9in%E5%A5%88%E8%89%AF2mini.jpg)
[高専カンファレンスin松江2](http://kosenconf.jp/?plugin=attach&refer=052matsue&openfile=conf.PNG)

**Comment by pndcat** [comment]
文字に起こしたほうがいいじゃんって思ったので，文字で表すとこんな感じでした

新春カンファレンスのポスター中身
- イベント名
- 日時
- 場所
- 参加費用
- 基調講演者
- 特別講演者
- 開催要項
- 参加登録方法(QRコードで)
- お問い合わせ

カンファin奈良2ポスター中身
- イベント名
- 日時
- カンファについて
- 日時
- 場所
- 費用
- 講演者
- 参加登録(URL)
- 一般発表，LT，企業参加型プレゼンの説明

カンファin松江2
- 高専カンファについて
- 時間
- 開場
- 参加費
- 基調講演者
- 詳細情報(URLのみ)
- "高専カンファ 松江"で検索
- 日時
- QRコード←何のQRコードかわからない

**Comment by denari** [comment]
書いた
