### ISSUE TITLE
発表形式の検討

### ISSUE THREAD

**Issue by tochikuji** [kosenconf-2015-tokyo/kosenconf#16]
会場のB棟は2階に大きな講堂が2つと小さなフリースペースが2つ、
1階に中講義室が3つ、大きなフリースペース(ホワイトボード等あり)があります。

せっかくB棟すべて借りられたんですから複数発表形式にしてみる、
アンカンファ形式、LTthon形式みたいなのも考えられるかもしれません。

**Comment by pndcat** [comment]
当日行う企画
- 基調講演
- アイスブレイク（複数部屋使用）
- 夢これ
- 複数トラック発表（複数部屋使用）
- 一般発表・LT
  で決定．

これより詳細は各チームで決めてもらうので閉じます．
