### ISSUE TITLE
基調講演の依頼

### ISSUE THREAD

**Issue by pndcat** [kosenconf-2015-tokyo/kosenconf#17]
おびなたさんといがいがさんにお願いする

**Comment by mactkg** [comment]
age @marin72-com

**Comment by mactkg** [comment]
お、失礼しました。

> 基調講演
> 
> おびなたさんに会って概要話した．
> けど，ちゃんと基調講演依頼メール考えて，slackに貼ります．
> いがいがさんの不明なところとかが出てきてたら，うなすけに説明お願いしたい
> https://github.com/kosenconf-2015-tokyo/kosenconf/wiki/20150906%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0#%E5%9F%BA%E8%AA%BF%E8%AC%9B%E6%BC%94

**Comment by pndcat** [comment]
こんな感じの文面はいかがでしょうか…
アドバイス欲しいです＞＜
よろしくお願いします！

---

五十嵐様
大日方様

高専カンファレンス100 in 東京 実行委員長の名渡山です．
突然の連絡ですみません．
今回はお二方に高専カンファレンス100 in 東京（以下 高専カンファ100）の
基調講演のご登壇の依頼のために，ご連絡致しました．

高専カンファ100の概要は以下となっております．
日時：12/19(土)・12/19(日)
場所：電通大 B棟
テーマ：Dreaming

高専カンファ100では，今までのカンファの良さを残しつつ
私達が考える新しいカンファを実現したいと考えています．
一般発表やLTに加えて，いくつかの企画を考えているのですが，
私を含め実行委員で「こんな基調講演にしたい！」と考えた結果，
五十嵐様と大日方様のＷ登壇型の基調講演を考えました．

今回のカンファレンスは東京で行うので，大規模になると予想しており，
初めての参加者も多いと見込んでおります．
そこで，お二方にご登壇して頂き，
カンファの始まりから現在に至るまでの歴史や，高専生って楽しいんだよ！など，
カンファ新規参入者が「カンファってこんな感じなんだ！楽しそう！」と
思ってもらえるような話をして頂ければと考えております．

基調講演は30分で，1日目 オープニングの次を予定しています．
そこでグッと参加者の心を掴んで欲しいです．

ご不明な点があれば，
五十嵐様は副実行委員長の中村に直接お聴き頂くか本メールにご返信をお願いします．
大日方様は日程を合わせてぜひご飯に行きたいです．

お忙しいところ大変申し訳ありませんが，ご検討のほどよろしくお願い致します．

**Comment by crimsonwoods** [comment]
おびさんは「大日方」じゃなくて「大日向」ですねー。
それから、この文面だと「W登壇型」の部分の説明が足りなくて2人の対話形式を希望していることが読み取れません。また発表内容を考えるにあたってもう少し会全体のテーマに関する説明があったほうが良いのではないかと思います。

「ご飯に行きたいです」のくだりはお二人を誘うのであれば良いのですが、おびさんだけを誘うものを宛先が連名のメールに書くのはどうかなと思います。

**Comment by pndcat** [comment]
くりむぞんさんのアドバイスを基に変更致しました．
すみませんが，ご意見よろしくお願いします．

---

五十嵐様
小日向様

高専カンファレンス100 in 東京 実行委員長の名渡山です．
突然の連絡ですみません．
今回はお二方に高専カンファレンス100 in 東京（以下 高専カンファ100）の
基調講演のご登壇の依頼のために，ご連絡致しました．

高専カンファ100の概要は以下となっております．
日時：12/19(土)・12/19(日)
場所：電通大 B棟
テーマ：Dreaming

高専カンファ100では，今までのカンファの良さを残しつつ
私達が考える新しいカンファを実現したいと考えています．
一般発表やLTに加えて，いくつかの企画を考えているのですが，
私を含め実行委員で「こんな基調講演にしたい！」と考えた結果，
五十嵐様と小日向様のＷ登壇型の対話式の基調講演を考えました．

従来の基調講演は，一人の方がパワポや動画を使って
最新のテクノロジー・留学・登壇者の体験談などを行うことが多かったですが，
高専カンファ100は，もっと高専カンファ風な基調講演にしたいと私達は考えました．
また，東京で行うので，新春カンファのような大規模開催になると予想しており，
初めての参加者も多いと見込んでおります．
そこで，お二方の雑談交じりのを対話式の基調講演で
カンファの始まりから現在に至るまでの歴史や，高専生の面白いところなど，
カンファ新規参入者が「カンファってこんな感じなんだ！高専生っていいな！」と
思ってもらえるような話をして頂ければと考えております．
『パワポはおまけでトークがメイン』のような基調講演がぜひみたいです．

基調講演は30分で，1日目 オープニングの次（12/19 13:10〜）を予定しています．
そこでグッと参加者の心を掴んで欲しいです．

ご不明な点があれば，
実行委員長の私，もしくは副実行委員長の中村に直接お聞き頂くか，
本メールにご返信頂ければお答え致します．

お忙しいところ大変申し訳ありませんが，ご検討のほどよろしくお願い致します．

**Comment by RooandQoo** [comment]
```
日時:12/19(土)・12/19(日)
場所:電通大 B棟
```

日曜は20日

電通大、じゃなくて電気通信大学、って表記したほうがフォーマル感出そう

**Comment by RooandQoo** [comment]
```
五十嵐様と小日向様のW登壇型の対話式の基調講演を考えました.
```

五十嵐様と小日向様おふたりにご登壇いただく「対話式の基調講演」を実現したい,という運びになりました.

「考えた結果〜考えました」っていうのがちょっと引っかかったので

**Comment by crimsonwoods** [comment]
おびさんは「大日向」ですよー

**Comment by pndcat** [comment]
五十嵐様
大日向様

高専カンファレンス100 in 東京 実行委員長の名渡山です．
突然の連絡ですみません．
今回はお二方に高専カンファレンス100 in 東京（以下 高専カンファ100）の
基調講演のご登壇の依頼のために，ご連絡致しました．

高専カンファ100の概要は以下となっております．
日時：12/19(土)・12/20(日)
場所：電気通信大学 B棟
テーマ：Dreaming

高専カンファ100では，今までのカンファの良さを残しつつ
私達が考える新しいカンファを実現したいと考えています．
一般発表やLTに加えて，いくつかの企画を考えているのですが，
私を含め実行委員で「こんな基調講演にしたい！」と考えた結果，
五十嵐様と大日向様おふたりにご登壇いただく「対話式の基調講演」を実現したい，という運びになりました.

従来の基調講演は，一人の方がパワポや動画を使って
最新のテクノロジー・留学・登壇者の体験談などを行うことが多かったですが，
高専カンファ100は，もっと高専カンファ風な基調講演にしたいと私達は考えました．
また，東京で行うので，新春カンファのような大規模開催になると予想しており，
初めての参加者も多いと見込んでおります．
そこで，お二方の雑談交じりの対話式の基調講演で
カンファの始まりから現在に至るまでの歴史や，高専生の面白いところなど，
カンファ新規参入者が「カンファってこんな感じなんだ！楽しそう！」と
思ってもらえるようなお話をして頂ければと考えております．

基調講演は30分で，1日目 オープニングの次（12/19 13:10〜）を予定しています．
そこでグッと参加者の心を掴んで欲しいです．

ご不明な点があれば，
実行委員長の私，もしくは副実行委員長の中村に直接お聞き頂くか，
本メールにご返信頂ければお答え致します．

お忙しいところ大変申し訳ありませんが，ご検討のほどよろしくお願い致します．

**Comment by pndcat** [comment]
五十嵐様
大日向様

高専カンファレンス100 in 東京 実行委員長の名渡山です．
突然の連絡ですみません．
今回はお二方に高専カンファレンス100 in 東京（以下 高専カンファ100）の
基調講演のご登壇の依頼のために，ご連絡致しました．

高専カンファ100の概要は以下となっております．
日時：12/19(土)・12/20(日)
場所：電気通信大学 B棟
テーマ：Dreaming

高専カンファ100では，今までのカンファの良さを残しつつ
私達が考える新しいカンファを実現したいと考えています．
一般発表やLTに加えて，いくつかの企画を考えているのですが，
私を含め実行委員で「こんな基調講演にしたい！」と考えた結果，
五十嵐様と大日向様おふたりにご登壇いただく「対話式の基調講演」を実現したい，という運びになりました.

従来の基調講演は，一人の方がパワポや動画を使って
最新のテクノロジー・留学・登壇者の体験談などを行うことが多かったですが，
高専カンファ100は，もっと高専カンファ風な基調講演にしたいと私達は考えました．
また，東京で行うので，新春カンファのような大規模開催になると予想しており，
初めての参加者も多いと見込んでおります．
そこで，お二方の雑談交じりの対話式の基調講演で
カンファの始まりから現在に至るまでの歴史や，高専生の面白いところなど，
カンファ新規参入者が「カンファってこんな感じなんだ！楽しい！高専生いい！」と
思ってもらえるようなお話をして頂ければと考えております．

加えて，今回のテーマが「Dreaming」なので
高専生の時に抱いてた夢や，その後何をしたのか，今はどんな夢を持っているのかを
お話して頂きたいです．

私は新春カンファに参加して，たくさんの人と出会いました．
あのとき受けた強い刺激があるからこそ今の私がいて，
これからも先輩方を尊敬し，目標にし続けると思います．
この気持ちを少しでも現役高専生・カンファ新規参入者に体験して欲しいです．
もっともっと刺激を受けて，自分の夢(目標)を持って欲しいという思いで
高専カンファ100のテーマとしました．

基調講演は30分で，1日目 オープニングの次（12/19 13:10〜）を予定しています．
そこでグッと参加者の心を掴んで欲しいです．

ご不明な点があれば，
実行委員長の私，もしくは副実行委員長の中村に直接お聞き頂くか，
本メールにご返信頂ければお答え致します．

お忙しいところ大変申し訳ありませんが，ご検討のほどよろしくお願い致します．

**Comment by kawataso** [comment]
> 従来の基調講演は，一人の方がパワポや動画を使って

突然の製品名略称は違和感を覚えるので無難にスライドや動画、がよいかと

**Comment by pndcat** [comment]
かわたそさんのアドバイスを修正した以下の文章で，メールを送信します．

---

五十嵐様
大日向様

高専カンファレンス100 in 東京 実行委員長の名渡山です．
突然の連絡ですみません．
今回はお二方に高専カンファレンス100 in 東京（以下 高専カンファ100）の
基調講演のご登壇の依頼のために，ご連絡致しました．

高専カンファ100の概要は以下となっております．
日時：12/19(土)・12/20(日)
場所：電気通信大学 
テーマ：Dreaming

高専カンファ100では，今までの高専カンファの良さを残しつつ
私達が考える新しい高専カンファを実現したいと考えています．
一般発表やLTに加えて，いくつかの企画を考えているのですが，
私を含め実行委員で「こんな基調講演にしたい！」と考えた結果，
五十嵐様と大日向様おふたりにご登壇いただく「対話式の基調講演」を実現したい，という運びになりました.

従来の基調講演は，一人の方がスライドや動画を使って
最新のテクノロジー・留学・登壇者の体験談などを行うことが多かったですが，
高専カンファ100は，もっと高専カンファ風な基調講演にしたいと私達は考えました．
また，東京で行うので，新春カンファのような大規模開催になると予想しており，
初めての参加者も多いと見込んでおります．
そこで，お二方の雑談交じりの対話式の基調講演で
カンファの始まりから現在に至るまでの歴史や，高専生の面白いところなど，
カンファ新規参入者が「カンファってこんな感じなんだ！楽しい！高専生いい！」と
思ってもらえるようなお話をして頂ければと考えております．

加えて，今回のテーマが「Dreaming」なので
高専生の時に抱いてた夢や，その後何をしたのか，今はどんな夢を持っているのかを
お話して頂きたいです．

私は新春カンファに参加して，たくさんの人と出会いました．
あのとき受けた強い刺激があるからこそ今の私がいて，
これからも先輩方を尊敬し，目標にし続けると思います．
この気持ちを少しでも現役高専生・カンファ新規参入者に体験して欲しいです．
もっともっと刺激を受けて，自分の夢(目標)を持って欲しいという思いで
高専カンファ100のテーマとしました．

基調講演は30分で，1日目 オープニングの次（12/19 13:10〜）を予定しています．
そこでグッと参加者の心を掴んで欲しいです．

ご不明な点があれば，
実行委員長の私，もしくは副実行委員長の中村に直接お聞き頂くか，
本メールにご返信頂ければお答え致します．

お忙しいところ大変申し訳ありませんが，ご検討のほどよろしくお願い致します．
