### ISSUE TITLE
公開連絡先の変更を事務局に依頼する

### ISSUE THREAD

**Issue by pndcat** [kosenconf-2015-tokyo/kosenconf#18]
tokyo2016[at]kosenconf.jp
から転送をして頂くようにお願いしてるけど，
tokyo2015[at]kosenconf.jp
がいいよね

**Comment by pndcat** [comment]
やっぱり100入れてもいいかも
- tokyo100[at]kosenconf.jp
- 100[at]kosenconf.jp

**Comment by mactkg** [comment]
https://github.com/kosenconf-2015-tokyo/kosenconf/wiki/meeting002_20150906#%E3%81%9D%E3%81%AE%E4%BB%96
復旧完了したら `tokyo100@kosenconf.jp` にしてもらう

**Comment by pndcat** [comment]
復旧連絡はきていない．
けど，
kosenconf100[at]googlegroups.com
に変更したので，問題ないと思います．
