### ISSUE TITLE
実行委員の担当を決める

### ISSUE THREAD

**Issue by pndcat** [kosenconf-2015-tokyo/kosenconf#21]
実行委員こんな感じに別れるのかなって思っています．
- アイスブレイク(1日目)
- 夢これ(1日目)
- 複数トラック発表(2日目)
- 一般発表・LT(2日目)
- 会計・物品
- 受付・広報
- 会場ネットワーク・配信
- 会場設営
- 懇親会
- 助っ人
# アイスブレイク(1日目)
- [Wikiに書いています](https://github.com/kosenconf-2015-tokyo/kosenconf/wiki/%E3%82%A2%E3%82%A4%E3%82%B9%E3%83%96%E3%83%AC%E3%82%A4%E3%82%AF)
- 第二回MTGで決まったものまで更新しました（9/14 15時更新）
# 夢これ(1日目)
- [Wikiに書いています](https://github.com/kosenconf-2015-tokyo/kosenconf/wiki/%E5%A4%A2%E3%81%93%E3%82%8C)
- Wikiは更新しました（9/14 16時更新）
- 発表に縛りを入れて欲しい（[ふるコン](http://kosenconf.jp/?038tokyo#v979f05c)を参照）
- 前の話し合いでは，チームにするか？という案が出た．  
- 実行委員長個人的な意見としては，チームだと夢を語りにくいかなと思い始めてきました
# 複数トラック発表(2日目)
- [Wiki書きました](https://github.com/kosenconf-2015-tokyo/kosenconf/wiki/%E8%A4%87%E6%95%B0%E3%83%88%E3%83%A9%E3%83%83%E3%82%AF%E7%99%BA%E8%A1%A8)(9/14 16時作成)
# 一般発表・LT(2日目)
- 一般発表25分 x 2人
- LT 5分 x 9人
- 今回のLTは時間きっかりにしたい
# 会計・物品
- お金の管理
- 事務局とのやりとり
- 実行委員長はあまりわからないので，実行委員やったことある人にお願いしたい
# 受付・広報
### 必ず必要なもの
- 当日の受付について考える
- プレス
- ポスター
### 希望
- **ロゴ考えたい！！！**
- ステッカーとか実行委員の洋服とかほしいなー
# 会場ネットワーク・配信
- 当日のネットワーク管理
- 配信
# 会場設営
- プロジェクター準備
- マイク確認
- 受付周辺(ロビー部分)に何か飾って欲しい（企画がほしい）
- [全国高専マップ](http://i0.wp.com/img.logmi.jp/wp-content/uploads/2015/07/gazou01117.jpg)みたいな企画をやってほしい
- そういえば第一回MTGでふるコンから派生して，写真コンテストみたいな企画あったよ（丸投げ
- **サブスクリーンもお願いしました**
# 懇親会
- 受付
- 集金のタイミング
- 当日参加者の対応を考える
- 交流企画考えよう
# 助っ人
- 各チーム，わからないことがあったら聞かれる人
- つらそうなチームがあったら一緒にやる人
- 足りないないことを探して各チームに投げる人
- うなすけはここで

**Comment by pndcat** [comment]
希望と主観で決めました．  

すずよしは旅行中だったので，個人的に連絡を取って，**一般発表・LT(2日目)**と**配信**の両方をお願いしました．

今気になるのは，**会場設営**，**会計・物品**チームが先輩方1人になってしまったことです．
ノウハウを溜めたいので，先輩メイン+21歳組の誰かがサブかけもちしてほしいなーとか思っています（まっくん，とちくじくんあたりかけもちしてくれませんかね）  

## アイスブレイク(1日目)
- mktakuya
- くりむぞん

## 夢これ(1日目)
- るーくちゃん
- まっくん

## 複数トラック発表(2日目)
- とちくじ
- いちごおれ

## 一般発表・LT(2日目)
- べーた
- すずよし

## 会計・物品
- はるかさん

## 受付・広報
- 中垣
- かじき

## 会場ネットワーク・配信
- かわたそ
- すずよし

## 会場設営
- あそなす

## 懇親会
- ありたそ

## 助っ人
- うなすけ

**Comment by unasuke** [comment]
:ok_woman:

**Comment by pndcat** [comment]
これでいきたいと思います！！
がんばりましょー！！！

まずは各チーム，[最低限これだけ守って](https://github.com/kosenconf-2015-tokyo/kosenconf/wiki/%E5%90%84%E3%83%81%E3%83%A3%E3%83%B3%E3%83%8D%E3%83%AB%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)いいかんじにchannelを立ててくださいませ〜

## アイスブレイク(1日目)
- mktakuya
- くりむぞん

## 夢これ(1日目)
- るーくちゃん
- まっくん

## 複数トラック発表(2日目)
- とちくじ
- いちごおれ

## 一般発表・LT(2日目)
- べーた
- すずよし

## 会計・物品
- はるかさん
- まっくん

## 受付・広報
- 中垣
- かじき

## 会場ネットワーク・配信
- かわたそ
- すずよし

## 会場設営
- あそなす
- とちくじ

## 懇親会
- ありたそ

## 助っ人
- うなすけ
