### ISSUE TITLE
日付を決める

### ISSUE THREAD

**Issue by pndcat** [kosenconf-2015-tokyo/kosenconf#3]
新春カンファぐらいの時期よかった．
成人の日(1/11)の次の土日(1/16 - 1/17)だと，いろんな人参加しやそう

けど，とりあえず場所決めてからですね

参考
新春カンファ
2012/1/14(Sat) - 2012/01/15(Sun)
成人式
2012/1/9(Mon)

**Comment by unasuke** [comment]
## 日付について

日付についてなのですが、今候補に上がっているのが、2016/01/16(土)から01/17(日)の両日開催です。
この予定でよろしいでしょうか？また、二日間の開催ということでよろしいでしょうか？

**Comment by pndcat** [comment]
日付：1/16-1/17 賛成
両日：やりたい
コメント：新春カンファの実行委員してないので，どんだけしんどいのかってのがわからないのですが，気持ちとしては両日やりたいです．

**Comment by pndcat** [comment]
場所を電通大にする場合，1/23 - 1/24 の週になる

**Comment by pndcat** [comment]
電通大B棟
