### ISSUE TITLE
〆切までに申し込み内容が空のひとに送るメールについて

### ISSUE THREAD

**Issue by betachelsea** [kosenconf-2015-tokyo/kosenconf#32]
11/03: 今のところ内容が空のひとはいらっしゃいませんが一応

```
title: [高専カンファレンス100 in 東京] 発表内容補完のお願い
----
XX 様
高専カンファレンス100 in 東京 運営事務局です。
(LightningTalk / 一般)発表へのお申し込みありがとうございます。

応募者締切は11月20日に設定させていただいておりますが、現時点でXX様の発表タイトルが仮題となっているようです。
発表タイトルについてお決まりでしたら折り返しご連絡いただければ幸いです。
どうぞよろしくお願いいたします。

高専カンファレンス100 in 東京 運営事務局
```

それ以前に、下記諸々の理由で、締切前の補完のお願いはしなくてもなんとかなるのでは...と思い直したのですがいかがでしょう。
- ゆるく応募してね！という文言も追加したところでせっつくのはちぐはぐな行動？
-  LT/一般については現時点で応募者規定数に達しないので内容未定でも発表者確定になりそう
- もし応募者多数でも、学生以外は抽選ということにしてあるので、内容未定が発表者選定の基準になってはいけないと思う
- 事前に内容を知りたいというのは、アンチハラスメントポリシーについての対策という観点が大きい？ それだったらその辺の理由周知と合わせてn日までにスライド送ってねっていうのが良いのでは

**Comment by betachelsea** [comment]
@marin72-com 11/13のリマインド、提案してもらったのですが改めて考えると上記のようなことが思い出されてきたんですが、いかがでしょう。
一旦そのまま11/20を待とうかと思うのですが...。

**Comment by betachelsea** [comment]
@marin72-com  こちらについて（リマインドやっぱり不要では説）はいかがでしょうか？ 一旦乗っかっておいて、すいません :bow:

**Comment by pndcat** [comment]
すみません，今確認しました

個人的には，リマインダがあると親切だなあと印象だなあと思うのですが，

> ゆるく応募してね！という文言も追加したところでせっつくのはちぐはぐな行動？
> というご意見もあるんだなあと思いました．

LTチームが，やっぱりこれは適切じゃないと思うなら，送らなくて大丈夫だと思います！
せっかく文章考えていただいたのにすみません＞＜

**Comment by betachelsea** [comment]
ううーん、じゃあ、一旦送らない方針とさせていただこうかな。
もしギリギリになって募集殺到!!! みたいな嬉しい悲鳴の場合はまた別途発表内容教えてくださいメールが必要だと思いますので、そのときにまた相談させてください！
closeしておきます。
