### ISSUE TITLE
11/20 翌日くらいに送る発表応募者へのメール文言確定

### ISSUE THREAD

**Issue by betachelsea** [kosenconf-2015-tokyo/kosenconf#33]
こんな感じでどうでしょう
↓
wiki に置きました
https://github.com/kosenconf-2015-tokyo/kosenconf/wiki/LT

**Comment by betachelsea** [comment]
# 気になってること
- 運営事務局って書き方で問題ないですか？
- というか「運営スタッフの柏です」って書き方にしたほうが良いですか？
- もし確定の場合、資料が事前にいついつまでに欲しいとかあったら書いておいたほうが良い気がしてきた
- 翌日は早すぎ？（まぁ翌日以降、という感じで）

**Comment by pndcat** [comment]
### 運営事務局って書き方で問題ないですか？

違和感は特に無いですが，わたしもわからないです…

### というか「運営スタッフの柏です」って書き方にしたほうが良いですか？

名前を名乗っていたほうが，発表者が名前を覚えてくれたりするので便利なのかなあとか思いました．
当日に困ったときに「柏さんは」とか言えそうだなあと．

### もし確定の場合、資料が事前にいついつまでに欲しいとかあったら書いておいたほうが良い気がしてきた

たしかに発表者側も提出があるのならば，スケジュールは把握しておきたいと思います．
連絡したほうがいいと思いますー！

### 翌日は早すぎ？（まぁ翌日以降、という感じで）

翌日で問題ないと思いますー
わたしだったら，連絡が早ければ早いほど，運営への信頼が上がります〜．

**Comment by unasuke** [comment]
> 運営事務局って書き方で問題ないですか？

僕的には運営事務局っていうとおっきな団体をイメージしがちなので、「実行委員会」とかでも良いと思いますが強い気持ちじゃないです :pray:

**Comment by betachelsea** [comment]
2人ともご意見ありがとうございます！

@marin72-com 

> 当日に困ったときに「柏さんは」とか言えそうだなあと

なるほど！と思ったので、変更してみました :smile: 
あとは実はwikiのほうに本名乗ってない（「べーた」で載ってる）んですが、まぁその辺はお察しですかね。それかべーた（柏）とでもしとこうかな...？

連絡翌日把握しました、このままの推移で人数不足確定だったらもうシュパッと送ろうかと思います。もうちょっと応募数増えないかどうか待ちたいところですが！笑

あと、スケジュール面については、アンチハラスメントポリシーとの兼ね合いもあるので、そこが詰められないと、思いました。web上での議論に限界があるようでしたら次回MTGで確認させてください。

@unasuke 
ナイス指摘です！！ :+1:  実行委員会にしました。（運営事務局って仕事で使ってる言い方で、そのまま指が出力しちゃった...。）
一応名乗り方についてはスタッフ各位の認識合わせがあるといいかなと思うので、後ほどgeneralチャンネルにも投げようかと思います!

**Comment by crimsonwoods** [comment]
高専カンファレンス事務局の方からきました。事務局おじさんです。

ということで`事務局`という呼称は`高専カンファレンス事務局`と混同される可能性があるので、今のように`実行委員会`など適当な表記が良いと思います。

細かい部分の添削は下記になります（私の主観で添削したものなので良いと思った部分だけ取り込んでもらえればと思います）。

## 発表OK

``` Markdown
title: [高専カンファレンス100 in 東京] 一般・LT発表：発表枠確定のご連絡
----
XX 様

高専カンファレンス100 in 東京 実行委員会 一般・LT発表担当スタッフの柏です。
(LightningTalk / 一般)発表へお申し込みいただきありがとうございます。

下記内容にてご発表をお願いさせていただきたいと思います。

発表枠： LT or 一般
発表タイトル： タイトル
発表者名： お名前

タイトル等のご変更をご希望される場合は本メールにご返信いただくか、下記連絡先までご連絡をいただけますようお願いいたします。また、何かご不明点がございましたらお気軽にお問い合わせください。

:よいかんじのれんらくさき:

発表順につきましては追って公式wiki上にて発表させていただきます。
また、発表タイトルおよび発表者名は公式wikiに掲載させていただく予定でおります。

スタッフ一同、当日のご発表を心より楽しみにしております。
どうぞよろしくお願いいたします。

高専カンファレンス100 in 東京 実行委員会
```

## 抽選漏れ

``` Markdown
title: [高専カンファレンス100 in 東京] 一般・LT発表についてのご連絡

----
XX 様

高専カンファレンス100 in 東京 実行委員会 一般・LT発表担当スタッフの柏です。
(LightningTalk / 一般)発表へお申し込みいただきありがとうございます。

今回、LT/一般発表へは規定枠数を超えるたくさんのご応募をいただいたため、
お申し込みをいただいた方々の中から抽選を行わせていただきました。
その結果、まことに残念ながらXX様からいただいたお申し込みにつきましては抽選から漏れてしまいました。このような結果となってしまい大変申し訳ございません。

// 注：複数トラック枠との兼ね合いで相談、でも複数トラックのほうが参加者多そうだなぁ

今回の高専カンファレンスでははアイスブレイク、夢これ、複数トラック発表等の様々な企画を用意しております。
皆様の心に残る「高専カンファレンス100 in 東京」となるよう準備を進めておりますので、発表者という形ではございませんが是非ご参加いただきたいと思います。

スタッフ一同、当日のご参加を心よりお待ちしております。
どうぞよろしくお願いいたします。

高専カンファレンス100 in 東京 実行委員会
```

こんな感じかなー。うーん。

**Comment by betachelsea** [comment]
@crimsonwoods  レビューありがとうございます！
一部ちょっと自分でも推敲しましたが、ほぼほぼ反映させていただきました。
また、一番上のほうをFix文としてぐりぐり編集するとrevisionsが取れないので、wikiのLTページ下部のほうにて最新の確定本文記入させていただきました。
https://github.com/kosenconf-2015-tokyo/kosenconf/wiki/LT

ブラッシュアップされてきた。ありがたやありがたや :pray:

**Comment by suzuyoshi9** [comment]
Slackの方でも書いたのですが、タイトルなどの変更云々の部分はGoogleフォームの再編集用リンクを運営側で取って、X月X日までに変更願いますといった感じにすればいいのではないかと思いました。
ただ、運営の方で確認しないと変更されたことがわからないかもしれないですね…
何か変更されたってことが分かる仕組み（メールとか？）があれば良いんですが。
（そもそも変更されたことを個別に把握する必要はないかも？）

**Comment by betachelsea** [comment]
とりあえずURL再取得可能なようにしましたー 回答シートの右端にボタンを設置しまして、そこをポチると全員分出るようにしました。（もしかしたら初回に権限関係のAccept警告が出るかもしれません）

X月X日までにここ経由で変更できますよーという話、自分はアンチハラスメントポリシー周りでどう動くか決めたら、そこも確定できるかなと思っています。変更されたということを能動的に知らなくても、そのXデーまでに絶対！確定お願いします！！という具合なら、その期日がすぎてなお「未定」扱いになっている人に個別にお願いに回ればよさそうなので。

ううーん、10日(火)に issue #34 をぜひ解決させたいですね。

**Comment by betachelsea** [comment]
無事送信完了しましたのでCloseします。
