### ISSUE TITLE
お問い合わせ対応

### ISSUE THREAD

**Issue by denari** [kosenconf-2015-tokyo/kosenconf#45]
# お問い合わせ内容
## お問い合わせ日

12/10
## 内容

```
1点、お伺いしたいことがありメッセージをお送りさせて頂いています。 
弊社ノベルティグッズの中に、弊社オリジナルの「エナジードリンク（250ml）」があります。
もし、当日参加の皆さんへ、イベント中または懇親会等にてお召し上がり頂けそうな機会がありましたら、
提供させて頂くことが可能です。ご検討の上、ご入り用でしたら、お気軽にその旨お知らせください。

※ご入り用の場合、郵送の都合上、12/15（火）までに一度メールにてご連絡を頂ければ幸いです。
```
# Slack上での議論ログ
#### なっちゃん

参加者が得するのはわかるのですが，今回のカンファは企業色出したくない！という思いでやってきたので，なくてもいいかなと思います．けど，今後のカンファ全てにおいて必要ないのか？というとそうではないと思います．だから，今回はやめておくけど，もし次回機会があればお願いします
#### でなり

僕はなっちゃんに同意です。
(当然極力感謝の意をお伝えしつつ、)今回はお断りするのが、なっちゃんが言っていた今回の方針にも沿っているし、これまで2社お断りしている以上は 一件認めるとそこに失礼だし、
なにより、彼らのイベントではないのに僕らがアメニティを配る道理がないでしょう
#### ありたそさん

僕はスポンサー枠でLTしたいとかいうわけでもないし、受付の横にサッと置いておくくらいならよいのでは思いました
欲しい人は勝手に持って行ってというスタンス
#### なっちゃん 2

そこねー
一応今回の話は「こんなことしたいんだけどエナジードリンク配るよ？どう？」っていう条件がない所なんですよね

"参加者にとって得する" というところに重きをおくべきか，"厳かな感じの高専カンファ" に重きをおくべきかと悩んだのですが，後者にしましたね…
#### るーくちゃんさん

面白いとは思うんですけど、僕もでなりくんと同意見です。
#### ありたそさん 2

となると、今回配るアメニティもカンファ公式のやつオンリーってかんじですかね
いつも雑にステッカーとか置いてあるから、今回もそんなスペースがあるのかなと勝手に思ってました
#### なっちゃん 3

カンファ公式のアニメティだとステッカーですかね
それを持ち帰ってもらいましょう〜

あと缶が増えるとゴミを持ち帰らない人とかもいるかもしれないので，そこも若干懸念していました．

**Comment by denari** [comment]
たとえばありたそさんの意見のように、「"ご自由にお取りください"専用のエリア的なものを用意して...」

みたいなスタンスで進めるならば、条件を設けて対応とかも手かと思い、条件として欲しそうなやつをまとめました。
1.  ほんとうに参加者だれもが勝手におけるようにすること
2.  参加者全体への事前アナウンスがあること。少なくとも14日中までには必ず
3.  たとえばなっちゃんのいうごみ処理のように、懸念事項をクリアできること
4.  見返りを一切求めてこないこと(LT枠など)

上記がクリアできれば、参加者どうしの交流のきっかけになるかもですし、やる価値が十分ありそうかと思っています。

---

③について補足、考えられうる考えられうる懸念事項
- ごみ処理
- 既に入稿済みであるリーフレットの地図への影響
  - たとえば大きなレイアウト変更が絡んでしまうと多少なり混乱を招きますよね。
- 大きな荷物の受け取り対応
  -  今回の問い合わせにかぎらず、どんなアメニティがくるかわからないので、ある程度対応してあげてもいいかも。ここは別に解消されなくても良いといえば良い気もしています。が、対応してあげるのが親切だし、彼らは対応してほしそう。

---

もう一点、重複にはなりますが、あえて意見を文字に残したいので補足、アメニティの配布方法はさまざまですが、受付で配るなどのこちらからの働きかけの要素が強い方法は僕は反対です。

理由は

> なにより、彼らのイベントではないのに僕らがアメニティを配る道理がないでしょう。

僕らの役割はあくまで、参加者に楽しんでもらうことかと思うので、「1参加者として、飲み物を配りたいから持ってくる」のは支援する、というスタンスを提案したいです。

**Comment by pndcat** [comment]
### 懸念事項
- ごみ処理
  - 蓋がない缶ってカバンに入れたくないし，持ち帰るの忘れる人がいそう
- 受け取りをどうするか
  - 200本近くの飲み物を運ぶのは不可能
  - 電通大に直接送るのも難しい
- 余ったらどうするか
  - 実行委員が持ち帰るのか？
  - 余った量にもよるけど，重くて持ち帰りたくないとか思いそう

**Comment by alitaso345** [comment]
@marin72-com 結局この件は

> 参加者が得するのはわかるのですが，今回のカンファは企業色出したくない！という思いでやってきたので，なくてもいいかなと思います．けど，今後のカンファ全てにおいて必要ないのか？というとそうではないと思います．だから，今回はやめておくけど，もし次回機会があればお願いします

今回のカンファではステッカーやチラシなど，各企業の人がもってきたものは全て断るという認識でいいですか？

**Comment by pndcat** [comment]
@alice345 
個人的に渡すとかなら良いのですが，受付においてくださいとかは断りたいです．

**Comment by denari** [comment]
@marin72-com 受付の隣におくのは良くない??ご自由においてくださいのスタンスで。それを過度に支援もしないけど。

**Comment by alitaso345** [comment]
@marin72-com 
ごみ処理問題 => もともとゴミ袋は用意する予定だったし，缶のためのゴミ袋もどうせ必要になるので特に問題なさそう

受け取り問題 => 自分たちで持ってくるならいいいです，大学に郵送とかはできませんと予め伝えた上でならこちらの手間になることはないのでは

余ったらどうするか問題 => 余ったら持ち帰ることも前提にすればいいのでは．ステッカーやチラシでも余ったら持ち帰ってもらいますし飲み物だけ特別扱いする必要もないかと

でなりくんの言うように「スペースはあるけどそれを支援する余裕はないよ」的なスタンスです

僕個人としては「ノベルティがあっても企業色ある高専カンファレンスにはならない」と考えているので，上記の意見を具申します．もしなっちゃんの中で「ノベルティは企業の色がでるからそれそのものがマズい」ということでしたら議論の余地は無いですが．

**Comment by pndcat** [comment]
中途半端にOKを出すよりも，すべてノーって言ったほうが楽だと思っています．
理由は変わらず「今回のカンファは企業色出したくない」からです．

なんでカンファで企業色出したくないのか考えてみたのですが，
- 大きい開催って企業じゃなくて，学校（高専）主体でやってるイメージ
- 高専生がやっている！という印象になる
- ここまで来たなら，自分たちだけで創りあげたい（NO 企業カラー）

と思っているからです．だいたいこんな感じ

---

なんかいろいろ企業について悩むところがあったんだけど，もうここまできたなら全部断って良いんじゃねって思ってしまいました
今までに2社断ってるし…

---

### ごみ処理問題

いや，お持ち帰りをしてもらいます．
#resources で話していたのは，実行委員が出すゴミについてです

### 受け取り問題

> ※ご入り用の場合、郵送の都合上、12/15（火）までに一度メールにてご連絡を頂ければ幸いです。

と書いているので，郵送じゃないですかね…

### 余ったらどうするか問題

たしかにそれは持ち帰ってもらうことでどうにかなりそうですね

**Comment by alitaso345** [comment]
あ，ごみ処理問題完全に勘違いしてました．すみません

**Comment by denari** [comment]
じゃあお断りする方向ですすめますか。KLabのイベントでなく、僕らのイベントだというスタンスは、とてもよいかと！

仮に万が一、彼らが勝手に持ってきた場合は、彼らの手で勝手に配る分には容認しても問題ないですかね？（ゴミ問題とかの観点から

**Comment by pndcat** [comment]
200本の飲み物について，「全部自分たちで持ってきて配って片付けて下さい」というのを条件に出すことになるんですよね
正直，いじわる（配らせる気ないからそんな条件を出してきた）に聞こえてしまうんですよね…

そんなことするよりも「もしかすると今後別の開催でお世話になるかもしれないので，今回は見送ります．次回また検討させて下さい」とかの方が，未来の開催時の可能性潰さないのかなとか思いました．

ステッカーは置いといて，飲み物はとりあえず断って良さそうと思いました．

**Comment by denari** [comment]
なるほど、確かに、良い言い方重要だ。「今回は」すっぱりお断りする方向で文章作って、Slackの#kouhouに貼るので、可能なら一度目を通してもらえると嬉しいです。#kouhou内でもレビューをして、通ればお返事します。
