### ISSUE TITLE
KPTを書く

### ISSUE THREAD

**Issue by asonas** [kosenconf-2015-tokyo/kosenconf#47]
スタッフ最後のク打ち合わせは別途やる（やるんだっけ？）として、まずは記憶が新しいうちにKPTをやりましょう。

KPTとは **Keep(次も活かしたいこと)** **Problem(問題だったこと)** **Try(挑戦したいこと・Pの対策)**の略です。それを各個人がこのIssuesにコメントをする形で記録を残しましょう。KPTを残すことである程度のナレッジを書き留めることもできるので、できたらみんな書いてくれると嬉しいです。

以下テンプレ

``` md
## Keep(次も活かしたいこと)

* 
* 

## Problem(問題だったこと)

* 
* 

## Try(挑戦したいこと・Problemの対策)

* 
* 
```

**Comment by asonas** [comment]
## Keep(次も活かしたいこと)
- 最後の打ち上げで maltineレコードが好きな人とお話できて最高だった
  - あと denari meets zoamichi できてて最高だった
- 全員分はなかったけどトランシーバが便利
- サブスクリーン運用できてよかった
- 3〜4年とかのレベルで久しく会ってない人とあえて大規模開催の集客力のすごさ
- 全体的にエモいトークからテックトークまであってよさ
- ネットワークが高品質で最高だった
- GitHub,Slackなど便利なツールを使いこなせていた
  - 後からスタッフになった人がひたすらメールを追う状況じゃなくてよかった...!!
- ミーティング会場を貸してくれる各社様
- 夢これのエモさ、アイスブレークのブレーキングさ。
- 物品リストつくってよかった。
- 

## Problem(問題だったこと)
- ドキュメント管理がIssueやWikiで大変だった
  - 熱い思いを綴った長文が急にくると心臓がバクバクする。
  - 
- 寝坊
- 最後にサブスクリーンが死んだ
  - キャパシティを考慮していなかった...無念...
  - LTはやっぱりツイートの流量が急増するっぽい
- トランシーバは便利だったけど、1階と2階で微妙に繋がりにくいことがあった
- RubyKaigi直後の高専カンファスタッフ業で死ぬかと思った。
- 4トラックは結構たいへんだったかも
- Slackにすべてのことが流れ過ぎていて、後追いするのが大変だった
  - 良い粒度のトピック（例えばデザインとか）はGitHub Issuesでやりとりしたほうがよかったと思う。

## Try(挑戦したいこと・Problemの対策)
- esa.ioを使いたい
  - Work In Progressのジャブ感
- Additionalなスポンサーを募ってみたい
  - ロビー的なところにコーヒーやお菓子のサービスしたい
- 事前に寝る
- トランシーバの中継器などがあれば繋がりにくい問題は解決しそうかも
- 発表をCFP形式で募ってみたい

**Comment by pndcat** [comment]
## Keep(次も活かしたいこと)
- **人と人がふれあうのを大事にしたカンファだった**
  - Twitterシール
  - 懇親会の名札裏に名前もらう
  - アイスブレイク
- 受付がすごく対応良かった
  - 参加者の困ったことがあったら受付にと周知した
  - 実際は実行委員も困ったら受付に声をかけたりできた
  - 受付に人がいると安心できた
- 1日目の受付は臨機応変に対応している人が多かった
  - 13:30 まで外で立つ @alitaso
  - 延長して受付をする受付外のメンバー
- 当日の写真とか受付の様子を 公式アカでつぶやいてくれた
- 配信も受付に立ってくれたしありがたい
- デザイナーふたりは強かった
  - デザイナー同士で相談ができるのは強い！
- 忘れ物をきちんと渡せられた
- トランシーバーで連絡が取れたので、複数トラック発表・アイスブレイクではとても役立った
- 複数トラック発表が終わった後に、他の部屋をすべて片付けてくれたので、B202の片付けだけで済んだ
- 他人から借りた物をしっかり管理できた
- 持ち物がなくなるということがなかった
- 基調講演がよかった
  - 初参加者が多いので「高専カンファどんなものだ？」というのがわかりやすかったと思う
  - 高専カンファをよく知っているお二人だからこその空気だった
- ネットワーク快適
- サブスクリーンよい
  - お知らせ欄、すごくよかった
  - やっぱりTLいいっすね！
- 一般発表・LTが超さくさくいった！
- アンチハラスメントポリシー：新たな試みができたこと
- 過去の大規模開催でやっていたプレスを出せた
- 事前準備が多かったので、結構仕事ができた
- 学生メインってことだったけど、全体的にLT クオリティ高かったと思う
- 水戸先生がたくさん協力してもらえた
- 100カンファのはじまりのはじまりのときに、大日向さんに相談できたこと

## Problem(問題だったこと)
- 遅刻が多かった
- 複数トラック発表の概要をwikiに載せるのが遅れた
- 複数トラック発表の概要をwikiに載せたあとに周知できなかった
- アイスブレイクの当日準備不足
  - その場になってから初めて気づいた事が多い
    - ビニール袋ない問題
    - アイスブレイク紙を受付に組み込めていない
- 受付班の仕事が多すぎた
- 1日目の受付班の仕事の見積もりが甘かった
- 発表者から受けた質問を他の発表者に共有できなかった
- アンチハラスメントポリシー
  - なんでやるのかをきちんと周知できなかった
  - 発表者が決まった後に「アンチハラスメントポリシーやります！」の連絡は遅すぎる
- 懇親会登録と本会登録はわけないとわかりにくかった
- 実行委員長がやらなくてもいい仕事（本来なら各チームでやるべき仕事）までしていた
  - 例えばWiki の更新とか
  - 実行委員長はそういう仕事をするんじゃなくて、別の仕事をするべき・別のことに頭を使うべきだったと思う
- 司会がいない問題ね…
- 質疑応答の時にマイクを持っていけばよかった
- 夢これレターを1日目の終わりとか、2日目の始まりにもガンガン渡したらよかった
- デザイナーの入稿物が @denari に固まりすぎた
  - 入稿ミスとか起きた
- 入稿が18日到着でギリギリだった
- 荷物受け取りは @cathy の負担大きかった
- 電通大道迷い人多かった
- 13時丁度にはじめられなかった
- GithubのPRを実行委員長がOK 出すみたいなのを決めていなかった
- サブスクリーン担当が複数人いるべきか、@asonas に仕事を振るべきじゃなかった
- 受付、当日スタッフいてもよかったのでは？
  - 外は、当日スタッフ＋実行委員の2人体制でカバーしたら良さそう
- 会場の空調問題ね…
- どこまで会場の電源を支援するのかって決めていなかった
  - 当日パタパタしちゃった

## Try(挑戦したいこと・Problemの対策)
- 受付と広報チームが3人であの量だと、仕事を見落としちゃうので、受付・広報はチームとして分けたほうがいい
- デザインは独立したチームでいいと思う
  - そのほうが他のチームからも仕事をもらいやすい（デザイナーの余力があるなら）
- デザイン、1人だと相談できないと思うので2人
- 懇親会登録・本会登録をしっかり分ける
  - こちらは本会登録
  - こちらは懇親会登録
- 「Github のwikiはこう使う、フローはこんな風にする」をしっかり決める。
  - 例えば今回だと、Github のPR は各チームが出す
  - OKを押すのは委員長とか
- 当日スタッフでいいことは当日スタッフにお願いしてもいいと思う
- アンチハラスメントポリシーは高専カンファとしては初めてだったので、しっかり問題点・良かったところを今後のメモとして残す
- 大きい開催ならば、副実行委員長も担当に入るべきではない
  - 例えば、実行委員長に連絡がつかない時はどうするの？→副実行委員長に連絡を取る
  - 会場の電源を支援する問題みたいな、どこのチームが担当するのかわからない仕事がちょくちょく出てくるので、そういうのは副実行委員長とかがカバーすると良さそう
- 資料の共有
  - ミーティングの資料は、もっと早めに資料を作るべき
  - みんながどこに資料があるのかわかるような配慮を行うべき
  - こういうのは、実行委員長か副実行委員長のお仕事
- 当日仕事をもらったけど、何をするのかは当日にしかわからない
  - わりと受付は資料とかをしっかり用意してよかった
  - アイスブレイクとかは結構突貫的だったな
- めちゃくちゃ企業に出資してもらうような会
  - 参加者のお金減らしたい
  - 今回Klabエナジー配らなかったけど、そういうのあってもいいよね
- もっと足したいけど、とりあえずここまで

**Comment by betachelsea** [comment]
## Keep(次も活かしたいこと)
- Slack運用するイベント運営は初めてだったけど活用できていたと思う
- 実際に集合してMTGをするとある程度マイルストーン的に考えられて良かった
- アイスブレイク大変好評だったし、大変楽しかった！
- 夢これレターも現物がもらえるというのすごくいいなぁと感じた、最後の渡すところが素敵だった
- 懇親会のお片づけを生協さんにお願いできるのがありがたすぎた…。
- ネットワーク、配信班お疲れ様です、ハイクオリティでした！！
- 複数トラックも配信監視作業させてもらっていましたが、きっちり同時開始ができていてうまく回せていた印象、すごい
- 一般/LTについて
  - 接続確認はやっぱり大事、事前のメール案内が正解だった
  - 開始超直前に司会2名（なっちゃん、うなすけくん）、タイマー担当者（いちごおれくん）と軽く打ち合わせしたの、かなり重要ポイントだったと思う
  - 時間の見積もりがかなり正確だった。実際の発表時間n分 + 交代に1分が黄金時間?
  - 素敵な発表が集まった（すごく運が良かった）

## Problem(問題だったこと)
- アンチハラスメントについて
  - 運用するなら応募前から決めて告知すべき、応募後に運用する決定は良くなかった
  - 運用委員が各チームの寄せ集めだったので意思決定が難しかった
  - 運用委員で決めたことを実行に移す担当者が必要だった。例えば、終了後に対象者のところにいって素早く指摘する、などの動きをカバーする人員が決まっていなかった。
  - とにかく諸々要検討だったし、慣れが必要だと感じた
- wiki更新
  - 更新フローがややこしくて？いちいち手間取った印象
  - 記法が特殊なのもちょっと関係しているかも
  - 多分気になった人がちょいちょいっと直して後からチームに伝達するくらいのゆるさで回ると思う
  - GitHubにおいてある.mdファイルは不要だと感じた
- 一般/LTについて
  - 抽選はしんどい
    - ギリギリまで集まり具合にヒヤヒヤしたし抽選は手間があった
    - 今回は学生優位にしたいという気持ちがあったので結果的には良かったが、先着順のほうが良さそう
  - 司会の負担が大きかった？（ごめんよ）
    - でも合間の保たせ方とか最高でしたのでやっぱり2人におまかせしてよかったと思いました、ありがとう！！ :bow: 
- 規定コンテンツ外のスピーチ類でも事前に分単位での扱いを決めておいてドラを運用する強靭な心臓が必要とされる
- メール文言考えるの苦手でしんどかった（個人の問題）

## Try(挑戦したいこと・Problemの対策)
- アンチハラスメントの運用はするなら応募開始前に決めよう
  - 難しいものなので、これに関するスタンスは、やるやらないを含めて各実行委員会で決定すればいいと思う
- wikiの更新は適宜で（同時更新作業に簡単に注意すればトラブルないと思う）
- 発表者は先着順で規定日に集まらなければ依頼する、くらいの気持ちがよさそう
- メール業はBCC送信を活用する。要送信前の指差し確認。

（あと、思いついたら更新します）

**Comment by 625tk** [comment]
## Keep(次も活かしたいこと)
- ネットワークが快適だった
- 複数トラック発表での15分制約を守れた
- これだけ大きな規模だったのに最終的に参加者の忘れ物がほぼなかった
- 初参加だったが、楽しめた
- アイスブレイクでブレイクできた
- クロージングで部屋を暗くしたの、クロージング感があってよかった
- どの物品が誰から借りたものかをしっかり管理できていた
- このカンファを機に新たなカンファが生まれた

## Problem(問題だったこと)
- Slackで流れてしまったものを探すのが大変だった
- 複数トラックの概要をwikiに載せるのを前日まで忘れていた
- トランシーバーの通信範囲
- 1日目の開始時間が遅れた
- 1日目の朝の受付でドタバタしてしまった
- 名札にtwitterの@だけでなくfacebookのページ名があっても良かったのではないかと思った
- 一部教室が寒かった
- LT,複数トラックの残り時間を発表者に見える向きでiPadを使って表示したがスタッフも確認したい。
- 複数トラックで借りた全てのiPadのロックについて考えられていなかった
- 2日開催、3連休の前半2日でやれると嬉しい

## Try(挑戦したいこと・Problemの対策)
- 各実行委員がどこにいるのかリアルタイムにわかりたい。
- 九州/東北からの参加が少なかったので増やしたい
- 

まだ更新します。

**Comment by mactkg** [comment]
## Keep(次も活かしたいこと)
- 夢これボードとか夢これレターとか不安だったけど結構良かった
  - スタッフが最初にいくつかやっておけば結構みんな参加してくれる
- 懇親会の交流デザインが良かった
  - いくつかやってみてよかったものをパターンにして使いまわせると良さそう
  - アイコンステッカーは話のきっかけになってよい
- 司会意外といけるぞ．こわくない．
- デザインすごいよかった．
  - いい人が見つかったら頼めると良いだろうと思う．
  - 大規模開催だと手に取れる形に物質化されるからデザイナーの皆さん的には面白かったりするのかなと思った．
- 会議中するどくつっこむtochikuji
- 実行委員長はびしっと仕事振っててよかった
- 僕は当日割とふらふらしてたけど，突然起こるイベントとかにふらっと対応できていた気がする
  - 大規模開催の場合はそういう人が居ると良いかも
- 大規模開催の場合はトランシーバーがあると便利

## Problem(問題だったこと)
- denariとcatchyの負荷の高さ
  - お金回りもう少し関わっても良かったかな...と反省．ありがとうございました
  - ただ個人的にそんなに関われる余裕がなかった
- サブのつもりで入ったら思ったより仕事あった
- 「誰が買うのか？」が明確じゃなかった
- 夢これが全体的に動くの遅かった
  - 他の皆さんのテンプレ助かりました．ありがとうございました
- 夢これ司会中，今どこが映っているのか把握できてなかった
- アンチハラスメントポリシーは誰が最終判断するのか
  - 発表中に発覚すると素早く判断しないといけない状況があるので，誰かちゃんと担当が居たほうが良いと思った．例えば各企画のリーダーとかで良い．

## Try(挑戦したいこと・Problemの対策)
- あと30分くらい懇親会長めにできないかな?
- 懇親会の乾杯時にスタッフも揃う状態になんとかできないかな?
- なんかスタッフ内の懇親会とかを開催前に何回か出来たらなあと思ったり
- また参加したいです．
- スポンサーしてもらっても良いんじゃないかな？と思った
- アンチハラスメントポリシーに関しては様々なカンファレンスが取り組み始めたのは最近だと思うし，積極的に困ったこととかを共有して行ったら良いと思う

また思いついたら更新します

**Comment by crimsonwoods** [comment]
## Keep(次も活かしたいこと)
- 若者主体の開催・運営（えねるぎっしゅで良い）
- 良いデザインはもちべーとしてくれる
- 語り場を作れた（と思う）
- 足りない部分を工夫やアイデアで補い合えたこと
- 実行委員の一体感（パーカー作って良かった）
- 参加者に楽しかったと言ってもらえた
- 新参の人たちに楽しんでもらえた
- 古参の人たちにも楽しんでもらえた
- 水戸先生みたいな味方がいてくれたこと
- ほぼ会場にゴミを残す人がいなかったこと

## Problem(問題だったこと)
- 二日間開催はやっぱりしんどいね
- いろいろ準備不足だったね
- やっぱり朝早いと人が来ないね（撤収作業を考えるとしょうがないけど）
- 受付は寒い
- スタッフを受付に張り付けすぎちゃう問題
- （たぶん）ネットワークも寒かった
- 足りない睡眠
- ゴミを会場近辺の居住者に押し付けちゃう問題

## Try(挑戦したいこと・Problemの対策)
- 二日間開催やるなら三連休のときにやろう
- 当日やることタイムテーブルとか当日必要なものリストとか当日の物品配置リストみたいなの作ったらよかったかな
- 冬季開催時はホッカイロとかハロゲンヒーターとか可能なら用意した方がよいね
- 受付をミニマムの人数でまわすのはやめよう
- スタッフも各自でだしたゴミは各自で持ち帰りましょう（基本的に）

## Memo
- アイスブレークに途中参加してくれたうなすけくんGJ
- アイスブレークの企画会議でうなすけくんと漫才してたなっちゃんもGJ
- かわたそねっとわーくGJ
- 発表申込者とのやりとりがおおよそ迅速だった（みんなちゃんと睡眠はとってね！）
- 配信の映像音声の品質が良かった

**Comment by unasuke** [comment]
## Keep(次も活かしたいこと)
- ともあれ、無事に終えることができた
- 素晴らしい小物
  - リーフレット、夢これレター、ステッカー
- ブログ書いてくれる人多い
- アンチハラスメントポリシーが生まれた

## Problem(問題だったこと)
- アイスブレイクの準備開始が遅れた
  - mkくんへの気付きが遅れた
  - 受付に当日になって仕事が増えてしまい詰まる
- (今回の開催の問題点とは言いがたいが)公式Wiki罠がある
  - URLは短縮しないとダメ
- 2日目の撤収が遅れた
- アンチハラスメントポリシー
  - 参加者に萎縮が生まれた
  - 止めるべきかの迷い、まだ運用に不慣れな点
- wikiに更新履歴つけたほうが良かった……
- スタッフとして写真撮影する人を決めておけばよかった？(くりむぞんさんありがとうございます)

## Try(挑戦したいこと・Problemの対策)
- アンチハラスメントポリシー
  - そもそもどのように止めるべきか
- 素早く帰させる
  - もしくは名残を惜しむのはひとまず置いといて会計処理とか？
- 公式Wikiを改善できないか
  - Pukiwikiは開発が終了している
  - (移行先として)誰でも編集できるということを考えるとgithub pagesは厳しい
- 企業スポンサード高専カンファレンス
  - 企業発表枠
    - その企業の高専出身者に限る
- 記録班をつくる

**Comment by Surigoma** [comment]
## Keep(次も活かしたいこと)
- 配信のクオリティ
- デザインの統一性
- トラブル時の対応
  - 次の担当が来ない(本当は起きちゃいけないけど)
- 新規もちゃんと取り込めたこと

## Problem(問題だったこと)
- 山椒で遅刻🙇
- 配信の突貫工事
- 事前確認の足りなさ
- スタッフも一緒に参加するものでスタッフが集まらずに開始

## Try(挑戦したいこと・Problemの対策)
- 前日に体調が悪くなりそうなものは食べない
- 配信設備の確認
- 決定事項や確認事項のチェックリスト作成
- 一緒に参加するものの前に無線orSlackでのリマインド
  *フルHD画質での配信
- イベント系での機材貸借りネットワークの構築
  - 例えばGoogleスプレッドでの一覧作成

**Comment by denari** [comment]
## Keep(次も活かしたいこと)
- デザインが割と幅広くできた
  - ポスターやステッカーはまあ当然
  - 全国高専MAPと夢これレターは他の班が絡んでいたが、デザインさせてもらえてとても嬉しかった
  - 各種張り紙・名札・身分シールなど、細かいものもデザインできてよかった
- いろいろ意見を聞いたうえでデザインをできた
  - ポスターのとき
    - 4つ案をだしたら、回答をかなり細かくもらえた。おかげで@kaziki2との議論がしやすかった。もちろん回答のスピードもある程度早くてよかった
  - 身分シールのとき
    - かなり細かい部分にはなるが、実行委員長はじめ多くの意見をもらえて、デザインの合理性を再確認できた。個人的にはとても嬉しかった
- デザイナーが複数人だったが、デザインの方向をかなり統一できた
  - @kaziki2がうまく動いてくれた
    - (個人的にはおもうところあり、彼女にはそれを伝えているが、)100カンファのデザイナーとして、僕のデザインを綺麗に踏襲してくれたのはとても良かった
- 他のカンファで宣伝させてもらえた
  - 他のカンファレンスでの広報活動は、かなりいろいろ許された
  - KOFは突然チラシを配る許可がおりた
  - 金沢カンファも飛び込みLTを許可してもらえた
    - ついでにポスターも貼ってもらえている
- 高専などにてポスターを貼ってもらうための広報をまあまあできた。
  - 北陸は僕が攻めた
  - [成果を見たら一目瞭然...??](https://github.com/kosenconf-2015-tokyo/kosenconf/wiki/kouhou)
- 広報のアカウントが100カンファ感あるアイコンにできた
  - デザイナーとしてうれしい
  - 他のカンファでもやっていい雰囲気作りたい
    - もっとやっていい感じ出して、kosenconfの公式アカのフォロワーを増やせばいいと思う
- 受付にスクリーンがおいてあって自由ができた
  - ブログの画像なんかにもちょくちょく載っててよかった。
  - やっぱりそれっぽくなるし、いろいろ広報もできるので役に立つ

## Problem(問題だったこと)
- ポスターの完成が遅かった
  - そもそもアサイン2週ぐらいでポスターをアップしてfixできるほどスケジュールが開いている人もそうそう居ない。
    - と思うともっと遅れててもおかしくなかった。僕のアサイン前なのでなにがあったかはわからないけど何らかの反省は必要なのではないか??
  - スケジュールを考えることは本当に大事
  - 実際、金沢カンファではポスターを持ち込むことができず、LTという形のみでの広報となった
- もっとデザインできた部分はあった!!!
  - 他の実行委員から「デザイナーさん忙しそうだしね...」というセリフを聞く機会が多く
  - 「いや、忙しくねーよ」ってこっちから言いたかった。
    - 実際言ってはないけど、「忙しくないアピール」をしたケースも(夢これレター : 料金からデザインまで全て僕が調査した後に、これ作ります??と聞く手の回し方)
      - 明らかに非効率
      - もっとやれる雰囲気を出せたらよかった。
- 開催までの作業が大変な #design / #kouhou と 開催当日に忙しい #uketuke のコアメンバーが一緒なのは一見合理的だけど、大変だった。
  - 実際、#designはともかく、#kouhouは当日にも仕事はあるし、 #uketukeとの兼任は厳しかった。
  - #designと#kouhouはいっしょでも良い気はするけど、#uketukeは分離するべきだったのではないか
    - もちろん、「当日に受付としてシフトに入っているスタッフ」になるのは問題ない気はする(#kouhou ...どうなんだろう。)
- 受付のフロー確認が甘かった。
  - DoorkeeperのQR確認で懇親会参加の有無が確認できないことで直前にかなり焦った。
    - 受付で受け取った正しい金額が出せなかった一因でもある
    - そこで動けるスタッフが居たのはいいことだけど、それ以前に確認体制を反省すべきだった。
- 受付フローが当日に増えた
  - アイスブレイクの班分けのあの紙を配る工程
  - 当然僕らもそれ担当を割り振っていなかった
  - 受付のスタッフの数にマージンをとっていたのが活きたが良くはない
- 懇親会当日受付のフローぎめを甘くしていた
  - 受付で受け取った正しい金額が出せなかった一因
- Twitter公式アカウントのつぶやき少ない
  - もっと呟けたなあと反省
  - 1日1ツイート目指せたかもしれない
- 広報にてかなりの部分でなっちゃんに頼ってしまっていた
  - なっちゃんが個人的に頑張るのはとても素晴らしいこと。
  - 問題はそれをもっとプッシュしたり、あるいはなっちゃんが頑張る必要がない状況まで持って行けていなかったこと
- 当日の鍵の管理が結構ごちゃごちゃしていた

## Try(挑戦したいこと・Problemの対策)
- デザイン系のスタッフをもっと早くアサインさせたい!!
- 受付と広報・デザインのコアメンバーを切り分ける
- 受付の部分のフローを徹底
- 他の班との連携を強固に
  - 受付もデザインや広報も
- 積極的ツイート
  - 広報チームの個人垢もしかり(公式感はないけどハッシュタグをもりあげるために)
  - 公式アカウント然り
- 広報して良いネタをうまく知らせ合う環境づくり
  - 環境案
    - 広報チームが、企画書アップ段階で情報を共有していいか聞く
    - Tweetチャンネルなど作成して、「お、これツイートしようぜ」を受け付ける
- #key チャンネルなど当日チャンネル作成
  - すごく一元管理しやすそう
  - 話題の混線を防ぐいい解決策なのかも

**Comment by alitaso345** [comment]
## Keep(次も活かしたいこと)
- Twitterシール分かりやすくてよかった
- デザイナーさんを巻き込めた
  - アイコンステッカーしかり高専MAPしかり，僕が考えて実際のモノを考える部分はすべてデザイナーさんにお願いしたらいいかんじになってできてた
- KC Foundsで若者きてくれてた
- アイスブレイクのおかげでかなり交流しやすくなってたと思う．特に名前を言い合っていくはすごい気に入ってる．

## Problem(問題だったこと)
- アイスブレイクの巻物作ったり，最強人間作るときに全員がペンをもってるわけじゃなかったので全員が参加しやすくなるように話を振るのがとても難しかった
- でなりくんに「早めにプリンターの確認しておいてね」と言われてたのに結局したのが前日
- しかもそのときに赤色がうまくでないことが気が付き，その部分の解決は図れなかった
- 写真撮影から懇親会誘導までの流れと誘導してくれる人を決めるのが直前になってしまってバタバタした
- 調布付近の昼飯くえる場所，公開して話すきっかけにしてったほうが有意義だった

## Try(挑戦したいこと・Problemの対策)
- 懇親会でカンファおじさんと現役若者の交流がもっと活発になるようにしたい
- 100人以上の規模で2次会やるの大変だけど，酒飲みながら話をしたいしいろんな話を聞きたい．なんとかして2次会セッティング．

**Comment by cathy044** [comment]
## Keep(次も活かしたいこと)
- slackでの運営楽しい．他担当にもすごく話しかけやすい
- デザインとてもよかった
- デザイン物沢山(デザイナーさん超重要)
- 夢これレターが楽しかったから沢山書きました
- アイスブレイク企画のワクワク感．懇親会のとき話しかけるきっかけに
- 複数トラック発表，学会みたいなのに楽しい発表ばっかりで楽しい
- 懇親会で名札の裏に名前かくやつで知らない人に話しかけてもらえたの嬉しかった
- 参加者は困ったことがあったら受付へ，という感じだったけどあんまり困ることはなかった様子
- パーカー可愛い
- 懇親会班とは日本地図やTwitterアイコンの件もあって連携とれてた気がする

## Problem(問題だったこと)
- 受付物品に領収書入れ忘れ(ごめんなさい)
- 当日準備の遅れからの，看板についての注意事項の直接的な伝え忘れ(ごめんなさい)
- Doorkeeperチェックインで懇親会参加かどうか確認できなかった
- 受付としての各担当への連携(アイスブレイクの班分けとかミーティング時にどうするか確認すべきだった)
- 受付時間の延長による各担当の人たちの負担
- 当日slackみてる余裕あんまりなかった
- 道案内の経路もう一個必要だったかも…？

## Try(挑戦したいこと・Problemの対策)
- 受付シミュレーションは当日じゃなくて事前にやって問題ないか確認したほうがいいかも(受付同士の話し合いはSkype中心だったのでその辺できなかった)
- 開場時間のあとすぐオープニングではなく，あえて少し時間をあけて見積もったらオープニング見る人増えるかも(遅れてきた人は諦めてた様子だった)
- 懇親会２次会欲しいかも
- トランシーバー全員分あったりしたら嬉しいな…または，当日わかりやすい連携の取り方があると嬉しい
- 受付・広報(デザイナーさん)をわけて人数も増やしたい(ただし沢山連携はとりたい)
- 受付はもっと周りの班の状況みて連携をとるようにしたい
- 個人的に広報活動もっとやっときたかったなぁと思いました

**Comment by asonas** [comment]
カジキさんのKPTを受け取ったので転記します。

k
・パーカーで沢山案をだしたこと。
結果色んな人に良かったと言ってもらえた。
・2日目のお昼ご飯の時に色んな運営メンバーの方とお話できたこと
・さらに打ち上げで運営の方と仲良くなれたこと
・学生受付(自分の受け持っていた所)は割とスムーズにできた！

p
・運営メンバーの方の顔と名前が一致しなかった
・ステッカーもっと案出せばよかった…
・でなりさんとかたつむりさんに頼りっきりになってしまったこと
・前日準備〜カンファ打ち上げまでの3日間で運営メンバーと仲良くなれた(もっと初めから打ち解けられれば良かった…)
・赤紐呼びかけとTwitterアイコンシールへの促し忘れがち
・受付で口で伝えることが多かったのでもう少し工夫できたら良かった

t
・運営メンバーのアイスブレイク
・MTGで名札をみんなつけるとか
・本番前にMTGとかで受付シュミレーションとかしてみて確認

**Comment by tochikuji** [comment]
## Keep(次も活かしたいこと)
- デザイナー班つよい
- 水戸先生つよい
- トランシーバつよい
- slackつよい
- 複数トラック時間ピッタリ進められたのはよかった
- アイスブレイクはやっぱり良かった、懇親会賑やか

## \- 懇親会のお名前書く制度

## Problem(問題だったこと)
- 複数トラック4並行は少し多かったかも(部屋に人が少なくて寂しかった)
- 複数トラックの発表概要の周知、ﾔﾌﾟｼｰみたいにページを整備したい
  - 公式Wikiじゃ厳しい？
- 受付のマニュアルの整備、当日何したらいいか初め分からなかった
- **当日進行の細かいところは考えられてなかった気がする** (初めの司会の問題とか)
  - 当日の進行表 or 事前シミュレーションがあったほうが良かったはず
  - スケジュールが全体的にざっくりし過ぎていた感じはある
- アンチハラスメントポリシー (Mtgで詳しく)
- 宣伝枠とか事前に募ったほうが良かったのでは？

## Try(挑戦したいこと・Problemの対策)
- 懇親会の催し物はやっぱりあったほうが良かったかも
- サブスクリーンをもっと楽しくできるかも
- 常々思ってたけど配信を見てる人のフィードバックを参加者のそれと分離したい
- どう実現するかはわからないけど、当日全体を見渡して管制する人がいるとよいかも

順次追加します

**Comment by RooandQoo** [comment]
## Keep(次も活かしたいこと)

### 全体
- 大きな開催をかなり少人数で回すことが出来た（すごい）
- 何よりも新春カンファで沖縄からきたなっちゃんがこのカンファをやってくれたっていうのが嬉しかった
- 次の世代にカンファ魂（？）を繋げられたとおもう

### 準備中
- 実行委員長に、どういう思いでカンファを開催するのか早めに言語化してもらうことでスタッフの意識が揃ったように思う
- デザイナー陣がすごかった!!!
- Slackのやり取りは楽だった
- 細かなタームでミーティングがあったので進捗の管理がやりやすかった

### 当日
- パーカー良い
- アイスブレイクがよかった
- 物理的フィードバック（夢これレター）がもらえて嬉しかったし、やってよかった
- クロージングがエモかった
- 初日がコミュニケーション重視、２日目がカンファらしいカンファ、というメリハリが良かった
- 集合写真の「100」が良かった

## Problem(問題だったこと)

### 準備中
- デザイナータスク量が多そうだった
- ミーティングの回数が多かったために議事録まとめたり資料つくったりが大変そうだった
- 実行委員同士でごはんとかいきたかった
- まっくんとコミュニケーションとるのが遅かったために夢これは色々後手後手だった

### 当日
- 遅刻した
- 当日司会を設けていなかった（忘れてた…）
- 会全体のシミュレーションが足りてなかったように思う
- ぺちゃくちゃに慣れていないために発表時に困惑してる子たちがいてハラハラした
- 懇親会で全然はじめましてできなかった（自分の問題）
- 寒かったね……。
- 打ち上げ行けなかった :sob:

## Try(挑戦したいこと・Problemの対策)
- 人が遅刻しないためにはどうしたらいいんだろう
- 社会人めちゃ多いしスポンサードされまくる大型カンファも面白そうだなと思った
- ぺちゃくちゃの練習方法など事前に提示できればしたい

明日までにまだ増えるかも

**Comment by suzuyoshi9** [comment]
## Keep(次も活かしたいこと)
- 大きな問題もなく、無事にカンファレンスを終えることができた
- 杉通さんから借りれた色々な機材のおかげで、配信を無事行うことができた。
- Youtube Liveは初めてだったが、概ね問題なく配信できた
- ニコ生でも、配信できた
  - 2人でやったので無料延長を忘れてしまうことはほぼなかった
- 複数トラック発表の2部屋同時配信ができた
- スタッフのみんなが、きちんと配信されているか見ていてくれた（ありがとう！！）
- ネットワークがとても快適だった
- 色々なデザインの成果物がとても良い
  - @denari @kaziki2 Good Job 👍
- トランシーバでスタッフ間の連絡がうまく取れた
- LTと一般発表を時間どおりに終えることができた
- 電通大のB棟講義室を会場に選んで◎
  - 机にPCを置ける（ひざ上じゃなくて良い）
  - 電源がいくつか既に用意されていた
- Slackがとても便利
- Googleフォームも便利
- 実行委員長のモチベの高さ
  - なっちゃんの思いと意志の強さのおかげで、信頼してついていけた
- 少人数のスタッフ
  - 発言しやすいし、意見もまとまりやすい
  - まさに少数精鋭👏

## Problem(問題だったこと)
- 一般・LTのことをべーたさんに全て任せてしまっていた
- 新春の時と比べて、配信視聴者が少なかった気がする（12月だったから？）
- 配信の設営が、完全に突貫工事
  - カメラワークをもう少し考慮すべきだった
  - 事前に会場でリハーサルをしておきたかった
- カンファ当日の遅刻（寝坊です、ごめんなさい🙇）
- #kouhou #design #uketuke が仕事が多そうで大変そうだった
- アイスブレイクの班分けを受付で伝えるところ
  - 紙じゃなくて、あらかじめメールなどで伝えたほうがよかったのではないか
  - そうすればフローが減る

## Try(挑戦したいこと・Problemの対策)
- 実際の会場での事前ミーティングとリハーサル (1,2週間前くらいに)
- 大規模のカンファ開催用に、配信・ネットワーク機材の備品箱を用意する
  - #resourcesで少し話した
  - やるなら、誰がどこで管理するか？
- ハイビジョン画質での配信
- 配信NGのときのテロップ表示など（しばらくお待ちください的な画面を出す）
- 前夜ラジオなどのカンファ告知放送
- 配信参加者を巻き込めるような企画
- スタッフ同士の懇親会 （kc038gohanのような）

また思いついたら追加しますー

**Comment by kawataso** [comment]
## Keep(次も活かしたいこと)
- 来場者向け・配信向けネットワーク提供（ただし規模の身の丈にあったものをよく考える）
- 会場提供してくれる組織と友好的な交渉をする

## Problem(問題だったこと)
- 大規模開催に必用な機器の調達（今回はより大きな規模で使った機器の一部を借りた）
- ネットワーク関連をkawatasoがほぼ単独でやった（リソースが足りないのではなく人にタスクを割り振る能力の不足）

## Try(挑戦したいこと・Problemの対策)
- 次世代ネットワークスタッフ〜

**Comment by pndcat** [comment]
KPT書いて頂きありがとうございました！
振り返りMTGも行ったので、〆ます。
