### ISSUE TITLE
実行委員長をあと一人決める

### ISSUE THREAD

**Issue by pndcat** [kosenconf-2015-tokyo/kosenconf#5]
そもそもに3人いるのか？
必要ないならそのまま
必要ならば3人目を誰にするか考える

**Comment by RooandQoo** [comment]
3人いないといけないことは全くないし、強く開催したい意思のある人が実行委員長であるべきなので、普通に言い出しっぺの2人が実行委員長、でいいと思う

2015/07/06 NADOYAMA Natsuko notifications@github.com:

> そもそもに3人いるのか？
> 必要ないならそのまま
> 必要ならば3人目を誰にするか考える
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kosenconf-2016-tokyo/kosenconf/issues/5

## 

---

ラクエスク | [AtomicAge|CosmicRaise].net | 瓶底眼鏡女子同盟

佐々木 佳祐 / rooq
Twitter:@RooandQoo
Tel:090-1529-7102
Mail:sa2ki.k32@gmail.com
Web:http://rooandqoo.com

---

**Comment by pndcat** [comment]
ご意見ありがとうございます〜
るーくちゃんさんの言うとおり，むりやり3人にするよりも，2人でいいのかなあって思います．
なにかと問題が起きたら，また対策を練ろうと思います．
他の意見が1日なければ，issue閉じたいので，意見があればお願いしますー

**Comment by pndcat** [comment]
実行委員長は，わたしとうなすけでやります〜
がんばります〜
