### ISSUE TITLE
開催テーマを決める

### ISSUE THREAD

**Issue by suzuyoshi9** [kosenconf-2015-tokyo/kosenconf#6]

**Comment by mactkg** [comment]
一体何になるんでしょうね…!
実行委員長のお二人がどうしてkosenconfやりたい! と思ったのか知りたいです!

僕の個人的なイメージだと最近のkosenconfはおとなしめだったイメージが有ります。
(最近僕があんまりインターネット見てないのもあるとは思うんですが)

**Comment by pndcat** [comment]
実行委員長らしく（？）自由に書きます！！！

## テーマ名：再スタート

### テーマに込めた思い
- 大規模な高専カンファは，地方開催よりもたくさんの高専生，社会人，高専に興味をもっている人たくさんたくさんの人と出会って刺激を受ける．
- 絶対に新しい感動・驚き・喜びを得られる
- その場で「あー楽しかった」だけじゃなくて，さらに一皮自分で剥いて**新たな自分を形成してほしい！！！**

### 参加者にどう感じて欲しいか
- 自分は新春カンファにめちゃくちゃ影響を受けた（変われた）から，もっといろんな人に体験して欲しい
- 若い現役生に刺激をあげたい
- 自分たちみたいな高専カンファ好きっていう年代を作りたい

### 動機
- 4年前，自分は新春高専カンファに参加して，生まれ変わった
- →もっと広い世界が知りたくなったから東京の電通大に行った，周りの高専生がなにしてるか知りたくなった，高専生が大好きになった，

### 他のテーマ名
- 「生まれ変わる」とかでも，ニュアンスは近い
- 「今までの自分＋カンファでの衝撃→これからの自分」っていうニュアンスが欲しい

**Comment by mactkg** [comment]
第二回mtgでDreamingになった。
https://github.com/kosenconf-2015-tokyo/kosenconf/wiki/meeting002_20150906
