### ISSUE TITLE
どんな企画やるのか決める

### ISSUE THREAD

**Issue by pndcat** [kosenconf-2015-tokyo/kosenconf#9]
一般発表（15分かな）
LT（5分）

はあるとして，その他どうするのかを決める

**Comment by mactkg** [comment]
前回大きくやった東京開催のKPTを見返すと参考になりそうですね、と思ったのですが、
もしかしてqwikにあっただけかな…(だとすると消えてる! :scream_cat:)
どんな企画があってよかったとか、色々書いてあった気がしてます。

**Comment by suzuyoshi9** [comment]
前回の新春カンファの振り返りは↓にありますよー
https://docs.google.com/document/d/1hzHasVVI-I2Sx24dhoVWtLXGeNcuUoZqulyGO1cMU9c/edit

**Comment by mactkg** [comment]
おお、ありがとうございますー!

**Comment by pndcat** [comment]
### ふるコンよかった
- 発表の閾値が低い
- 発表方法が面白い（自動で流れていく）
- いろんな発表スタイルがあって面白かった
- 学科関係なくできた・学科関係なくわかる

本当にふるコン良かったなあと思っている人間なので，ふるコンみたいなのしたい

### 今回どうするか

わたしの持っているふるコンの印象は，**地方について詳しく話す**というところに重みがあったと思う
例えば，今回はもっと各高専に特化したような内容にする
- 高専の紹介（どこにあって，こんな学科がありますみたいな全体的な）内容
- 自分の所属する学科紹介（こんなところが変わっているの）
- 珍しい先生紹介
- こんな部活が頑張っていますとか
- 変な行事紹介
- 変な風習紹介
- 変な施設紹介

とかだったら，まあ発表の閾値を下げれて，だれでも発表できるのかなあ

**Comment by pndcat** [comment]
### 主に現役高専生向け：就活/進学支援とか

**現役高専生に来て欲しい〜〜〜〜〜〜**

就活もいろんなイベントあるし，最近だと編入向け進学支援だと[ZENPEN](http://zenpen.miraiserver.com/)が頑張ってると思う

#### 就職支援

今最前線で働いているエンジニアのプレゼンってすごくわくわくさせられるから，そういう話向けようをしてほしいなあとか思ったりする
単にわたしが聞きたいだけなのかもしれないけど

#### 進学支援
- ZENPENって有名大学（主に関東）が多い
- 発表とブースセッション

→いろんな編入生でパネルディスカッションっぽいカタチとかだと新しいのかなあ
あまりパネルディスカッション知らない人が多いと，だらだらの雑談に近いものにならないか心配

**Comment by pndcat** [comment]
# 1日目

## 基調講演

2人でお話してもらうスタイルにしよう
おびなたさん，いがいがさんにお願いする

## アイスブレイク

「あなたは校長先生になりました．みんなが入りたくなるような高専を作ってください」 

## ゆめコレ

夢について語る5分LT
発表形式に工夫して欲しい   

# 2日目

## 複数トラック発表

YAPC風
20分（15分発表 + 5分休憩）x 4トラック x 4 || 5回分

## 一般発表

25分 x 2本

## LT

5分 x 10本
